### ISSUE TITLE
Enforce that epoxy-images are not tagged before k8s master updates

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/epoxy-images#161]
One of the root causes of the pusher/TSO outage was due to epoxy-images creating new boot images that included later versions of k8s than the k8s master supported.

We should enforce that epoxy-images are only updated after a k8s master version is updated to support the client.

**Comment by nkinkade** [comment]
@stephen-soltesz: the only way I can think of, at the moment, to somehow enforce that an API cluster has been upgraded before building epoxy-images would be to somehow fetch a valid kubeconfig for the cluster during the build, query the cluster for version (something like `kubectl version --short=true`), then check the returned version against the version configured in config.sh in the root of this repo. This is doable, but seems a little clunky. What do you think? I'm thinking about this again, due to issue #199.
